# Generated by Django 6.0.4 on 2026-04-14 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mock_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("queue_number", models.PositiveIntegerField()),
                ("current_serving_number", models.PositiveIntegerField(default=0)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("browser_push_opt_in", models.BooleanField(default=False)),
                ("near_turn_threshold", models.PositiveSmallIntegerField(default=3)),
                ("near_turn_notified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("notified", "Notified"),
                            ("served", "Served"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="mock_api.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["institution__name", "queue_number"],
                "indexes": [
                    models.Index(
                        fields=["institution", "status"],
                        name="queue_track_institu_db57c2_idx",
                    ),
                    models.Index(
                        fields=["institution", "queue_number"],
                        name="queue_track_institu_589b88_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("current_serving_number__gte", 0)),
                        name="queue_current_serving_non_negative",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["waiting", "notified"])),
                        fields=("institution", "queue_number"),
                        name="uniq_active_queue_number_per_institution",
                    ),
                ],
            },
        ),
    ]
