# Generated by Django 6.0.4 on 2026-04-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueentry',
            options={'ordering': ['institution_id', 'queue_number']},
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='created_at',
        ),
    ]
