# Generated by Django 6.0.4 on 2026-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('bank', 'Bank'), ('government', 'Government Office'), ('utility', 'Utility Provider'), ('other', 'Other')], default='other', max_length=20)),
                ('api_endpoint', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'institution_type'), name='uniq_institution_name_per_type')],
            },
        ),
    ]
