# Generated by Django 6.0.4 on 2026-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="address",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed"), ("paused", "Paused")],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Administrative flag indicating whether this institution should "
                    "be enabled in the application, independent of its operational "
                    "status."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed"), ("paused", "Paused")],
                default="open",
                help_text=(
                    "Operational state of the institution (for example, whether it is "
                    "open, closed, or paused)."
                ),
                max_length=20,
            ),
        ),
    ]
