# Generated by Django 6.0.4 on 2026-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed"), ("paused", "Paused")],
                default="open",
                max_length=20,
            ),
        ),
    ]
