# Generated by Django 6.0.4 on 2026-04-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_api", "0002_institution_address_institution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed"), ("paused", "Paused")],
                default="open",
                max_length=20,
            ),
        ),
    ]
