# Generated by Django 6.0.4 on 2026-04-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('browser', 'Browser Push'), ('sms', 'SMS'), ('system', 'System')], max_length=20)),
                ('event_type', models.CharField(choices=[('near_turn', 'Near Turn'), ('turn_called', 'Turn Called'), ('session_expired', 'Session Expired'), ('generic', 'Generic')], max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('error_detail', models.TextField(blank=True)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='queue_tracker.queueentry')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['queue_entry', 'event_type'], name='notificatio_queue_e_83d9b9_idx'), models.Index(fields=['channel', 'delivered'], name='notificatio_channel_fff150_idx')],
            },
        ),
    ]
