"""
Django settings for queueless_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


IS_TEST_ENV = "PYTEST_CURRENT_TEST" in os.environ or any(
    cmd in sys.argv for cmd in ["pytest", "test"]
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret.
# Default DEBUG=True for local dev and CI. Production must set DEBUG=False.
DEBUG = env_bool("DEBUG", default=True)
ENABLE_MOCK_API = env_bool("ENABLE_MOCK_API", default=DEBUG)
DEV_SECRET_KEY = "django-insecure-dev-only-change-me"
SECRET_KEY = os.getenv("SECRET_KEY", DEV_SECRET_KEY)
if not DEBUG and not IS_TEST_ENV and SECRET_KEY == DEV_SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG is False.")

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()
]
if not DEBUG and not IS_TEST_ENV and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS must be set when DEBUG is False.")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "channels",
    "mock_api.apps.MockApiConfig",
    "queue_tracker.apps.QueueTrackerConfig",
    "notifications.apps.NotificationsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "queueless_backend.urls"

ASGI_APPLICATION = "queueless_backend.asgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "queueless_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

database_url = os.getenv("DATABASE_URL")
if IS_TEST_ENV:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
elif database_url:
    try:
        DATABASES = {
            "default": dj_database_url.parse(database_url, conn_max_age=600),
        }
    except ValueError as exc:
        raise ImproperlyConfigured(f"DATABASE_URL is invalid: {exc}") from exc
elif DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    raise ImproperlyConfigured("DATABASE_URL must be set when DEBUG is False.")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS configuration from environment variables.
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = [
    origin.strip().rstrip("/")
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

cache_url = os.getenv("CACHE_URL")
if cache_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": cache_url,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "queueless-default-cache",
        }
    }

try:
    QUEUE_AUTO_TICK_INTERVAL_SECONDS = int(
        os.getenv("QUEUE_AUTO_TICK_INTERVAL_SECONDS", "15")
    )
except ValueError as exc:
    raise ImproperlyConfigured(
        "QUEUE_AUTO_TICK_INTERVAL_SECONDS must be an integer."
    ) from exc

if QUEUE_AUTO_TICK_INTERVAL_SECONDS < 1:
    raise ImproperlyConfigured("QUEUE_AUTO_TICK_INTERVAL_SECONDS must be at least 1.")

QUEUE_AUTO_TICK_RANDOMIZE = env_bool("QUEUE_AUTO_TICK_RANDOMIZE", default=True)

try:
    QUEUE_GRACE_PERIOD_SECONDS = int(os.getenv("QUEUE_GRACE_PERIOD_SECONDS", "180"))
except ValueError as exc:
    raise ImproperlyConfigured(
        "QUEUE_GRACE_PERIOD_SECONDS must be an integer."
    ) from exc

if QUEUE_GRACE_PERIOD_SECONDS < 1:
    raise ImproperlyConfigured("QUEUE_GRACE_PERIOD_SECONDS must be at least 1.")

# Channel layer configuration.
# Use Redis in production (via CHANNEL_LAYER_URL) or InMemory for dev.
channel_layer_url = os.getenv("CHANNEL_LAYER_URL")
if channel_layer_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [channel_layer_url],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

# VAPID configuration for Web Push notifications.
VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY")
VAPID_ADMIN_EMAIL = os.getenv("VAPID_ADMIN_EMAIL", "admin@queueless.app")
